#UPDATE_FREQUENCY = 60*2 # 5 minutes
#RETENTION_TIME = 60*60*24 # 24h

UPDATE_FREQUENCY = 20
RETENTION_TIME = 60

DB_PATH = "../db/servers.db"
LOG_FOLDER = "../logs/"
LOG_FILE_EXTENSION = ".log"

RETRY_COUNT = 3
RETRY_DELAY = 2